[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    'kontrol-cheatcodes=lib/kontrol-cheatcodes/src',
]

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"

[fuzz]
runs = 1000
seed = '0x2'

[invariant]
runs = 64
depth = 32
fail_on_revert = false

# [profile.default.model_checker]
# contracts = { './src/CaughtWithSymbolic.sol' = ['CaughtWithSymbolic'] }
# engine = 'chc'
# timeout = 1000
# targets = ['assert']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
